name: Docker Build and Push

on:
  push:
    branches:
      - main  # Execute o workflow quando houver push na branch "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure o Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build da imagem Docker
      - name: Build Docker image
        run: |
          docker build -t rrsnaza/academic-blog:latest .

      # Push da imagem para o Docker Hub
      - name: Push Docker image
        run: |
          docker push rrsnaza/academic-blog:latest